language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv shell

# command to run tests and lint
script:
  - flake8
  - pytest # or py.test for Python versions 3.5 and below
